# Generated by Django 5.0.14 on 2026-04-26 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citoyenuser',
            name='username',
            field=models.CharField(blank=True, help_text='Optionnel. 150 caractères ou moins.', max_length=150, null=True, unique=True, verbose_name='username'),
        ),
    ]
