# Generated by Django 5.0.14 on 2026-04-30 02:38

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_citoyenuser_username"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="citoyenuser",
            managers=[
                ("objects", apps.accounts.models.CitoyenManager()),
            ],
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="adresse",
            field=models.TextField(blank=True, verbose_name="Adresse de domicile"),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="commune",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Commune / Sous-préfecture"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="genre",
            field=models.CharField(
                blank=True,
                choices=[("M", "Masculin"), ("F", "Féminin")],
                max_length=1,
                verbose_name="Genre",
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="mere_nom_complet",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom complet de la mère"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="nin",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                unique=True,
                verbose_name="NIN (Numéro d'Identification National)",
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="pere_nom_complet",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Nom complet du père"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="prefecture",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Préfecture"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="profession",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Profession"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="quartier",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Quartier / District"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="region",
            field=models.CharField(blank=True, max_length=100, verbose_name="Région"),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="secteur",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Secteur / Village"
            ),
        ),
        migrations.AddField(
            model_name="citoyenuser",
            name="taille",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=3,
                null=True,
                verbose_name="Taille (m)",
            ),
        ),
    ]
