# Generated by Django 5.0.14 on 2026-04-30 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_citoyenuser_managers_citoyenuser_adresse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="citoyenuser",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="citoyens/photos/",
                verbose_name="Photo d'identité",
            ),
        ),
    ]
