# Generated by Django 5.0.14 on 2026-04-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="piecejustificative",
            options={
                "ordering": ["uploaded_at"],
                "verbose_name": "Pièce justificative",
                "verbose_name_plural": "Pièces justificatives",
            },
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="fichier",
            field=models.FileField(
                upload_to="documents/pieces/%Y/%m/", verbose_name="Fichier"
            ),
        ),
        migrations.AlterField(
            model_name="piecejustificative",
            name="nom_original",
            field=models.CharField(max_length=255, verbose_name="Nom original"),
        ),
    ]
