# Generated by Django 5.0.14 on 2026-04-26 02:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandeDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=25, unique=True, verbose_name='Référence')),
                ('type_document', models.CharField(choices=[('CNI', "Carte Nationale d'Identité"), ('EXTRAIT_NAIS', 'Extrait de Naissance'), ('PASSEPORT', 'Passeport'), ('CERT_RESIDENCE', 'Certificat de Résidence')], max_length=20, verbose_name='Type de document')),
                ('statut', models.CharField(choices=[('RECUE', 'Demande reçue'), ('VERIFICATION', 'Vérification NaissanceChain'), ('SIGNATURE', 'Signature cryptographique'), ('PRET', 'Prêt au téléchargement'), ('REJETE', 'Rejeté')], default='RECUE', max_length=20, verbose_name='Statut')),
                ('blockchain_tx_hash', models.CharField(blank=True, max_length=100, verbose_name='Hash transaction blockchain')),
                ('blockchain_network', models.CharField(default='NaissanceChain', max_length=50, verbose_name='Réseau blockchain')),
                ('document_genere', models.FileField(blank=True, null=True, upload_to='documents/certifies/%Y/%m/', verbose_name='Document certifié')),
                ('qr_code_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Token QR code')),
                ('motif_rejet', models.TextField(blank=True, verbose_name='Motif de rejet')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Complété le')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='demandes', to=settings.AUTH_USER_MODEL, verbose_name='Citoyen')),
            ],
            options={
                'verbose_name': 'Demande de document',
                'verbose_name_plural': 'Demandes de documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PieceJustificative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(upload_to='documents/pieces/%Y/%m/')),
                ('nom_original', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('demande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces_justificatives', to='documents.demandedocument')),
            ],
            options={
                'verbose_name': 'Pièce justificative',
                'ordering': ['uploaded_at'],
            },
        ),
    ]
